#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

ESC=$(printf '\033')
RESET="${ESC}[0m"
YELLOW="${ESC}[33m"

local_branch="$(git rev-parse --abbrev-ref HEAD)"
echo "local_branch: $local_branch"

issue_number="$(echo $local_branch | egrep --only-matching '^[0-9]+')" || issue_number="" | echo "${YELLOW}WARN: branch name is not found.\n e.g.) 23-feat-description${RESET}"
echo "issue_number: $issue_number"

if [ -n "$issue_number" -a -z "`grep  "^\([a-zA-Z]\{1,\}:\) #$issue_number " $1`" ]; then
    echo "insert issue number in commit-msg"
    echo "$(cat $1 | sed "s/^\([a-zA-Z]\{1,\}:\) /\1 #$issue_number /")" > $1
fi
